version: "3.9"
services:

#  server:
#    build: back
#    ports:
#      - "8080:8080"
#    volumes:
#      - back:/app

  client_mobile:
    build: ./mobile
    ports:
      - "8082:8082"
    volumes:
      - ./mobile:/app
      - shared:/app/shared
#    depends_on:
#      - server

  client_web:
    build: ./front-web
    ports:
      - "8081:8081"
    volumes:
      - ./front-web:/app
      - shared:/app/shared
    depends_on:
      - client_mobile
#      - server

volumes:
  shared:
