#
# @brief Sign controller
# @description sign controller
# @author @Perry-chouteau perry.chouteau@epitech.eu
# @old commit https://github.com/Epi-Area/Area/commit/00f48e7ec5fea2945050ea2d883115cc443e140d
#

version: '3'

services:
  gateway:
    container_name: docker-gateway
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - sign-tier
    restart: unless-stopped

  sign:
    container_name: docker-sign
    build:
      context: ./services/sign
      dockerfile: Dockerfile
    ports:
      - "7001:7001"
    networks:
      - sign-tier
#      - database-tier
    restart: unless-stopped

# https://hub.docker.com/_/postgres
#  db:
#    container_name: docker-postgres
#    image: postgres
#    ports:
#      - "8000:5432"
#    environment:
#      POSTGRES_USER: user
#      POSTGRES_PASSWORD: password
#      POSTGRES_DB: db
#      PGDATA: /var/lib/postgresql/data/pgdata
#    volumes:
#      - ./db/data:/var/lib/postgresql/data
#    restart: unless-stopped

networks:
  sign-tier:
#    driver: bridge
#  database-tier:
#    driver: bridge

#volumes:
#  postgres: