<<<<<<< HEAD
version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: /run/secret/secret_username
      POSTGRES_PASSWORD: /run/secret/secret_password
      POSTGRES_DB: mydb
    secrets:
      - secret_username
      - secret_password
    ports:
      - '5432:5432'
=======
version: '3'
services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: area_database
    volumes:
      - pgdata:./data
volumes:
  pgdata:
>>>>>>> origin
