area:
  api-gateway:
    name: it
    version: 1.0
    type: node/express
    authentification:
      - google:
        base-url:
      - github:
        base-url:
    hostname: localhost
    port: 8080
    url: "/api/v1/"
  services:
    - name: sign
      type: node/grpc
      hostname: localhost
      port: 8001
      root:
        - url:
          type: GET
        - url:
          type: POST
        - url:
          type: GET
    - name: github
      type: node/grpc
      hostname: localhost
      port: 8002
      root:
        - url:
          type: GET
        - url:
          type: GET
      realUrl: https://docs.googleapis.com
    - discord:
    - google-doc:
    - youtube:
    - spotify:
    - twitter:
    - instagram: