apigateway:
  name: area-api
  description: null
  version: 1.0.2
  last-update: 19/01/2023
  url: null
  ip: 192.168.1.25
  port: 7357
  services:
    - name: sign
      ip: 192.168.1.25
      port: 7001
    - name: discord
      ip: 192.168.1.25
      port: 7002
    - name: github
      ip: 192.168.1.25
      port: 7003
    - name: outlook
      ip: 192.168.1.25
      port: 7004
    - name: google
      ip: 192.168.1.25
      port: 7005
    - name: twitter
      ip: 192.168.1.25
      port: 7006
