name: Flutter (mobile) test

on:
  push:
    paths:
      - mobile/**

jobs:

  flutter_test_android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
        with:
          fetch-depth: 0

      - name: Setup Flutter
        uses: subosito/flutter-action@v2.8.0
        with:
          flutter-version: '3.3.9'
      
      - name: flutter pub get
        run: cd mobile/ && flutter pub get

      - name: flutter test
        run: cd mobile/ && flutter test
  
  flutter_test_ios:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3.3.0

    - name: Setup Flutter
      uses: subosito/flutter-action@v2.8.0
      with:
        channel: 'stable'
        architecture: x64

    - name: flutter pub get
      run: cd mobile/ && flutter pub get

    - name: flutter test
      run: cd mobile/ && flutter test