name: basic

on: push

jobs:

  flutter_build_android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
        with:
          fetch-depth: 0
      
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2.8.0
        with:
          flutter-version: '3.3.9'
      
      - name: flutter pub get
        run: flutter pub get

      - name: flutter test
        run: flutter test

      - name: flutter build apk
        run: flutter build apk --released
  
  flutter_build_ios:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3.3.0

    - name: Setup Flutter
      uses: subosito/flutter-action@v2.8.0
      with:
        channel: 'stable'
        architecture: x64

    - name: flutter pub get
      run: flutter pub get

    - name: flutter test
      run: flutter test

    - name: flutter build ios
      run: flutter build ios --release --no-codesign

